modLoader="javafml"
loaderVersion="[43,)"
license="GNU LESSER GENERAL PUBLIC LICENSE"
licenseURL= "https://github.com/LeoBeliik/LittleBotanica/blob/master/LICENSE.txt"
issueTrackerURL="https://github.com/LeoBeliik/LittleBotanica/issues"
[[mods]]
modId="littlebotanica"
version="${file.jarVersion}"
displayName="Little Botanica"
authors="LeoBeliik"
description='''
mod do thing
'''
[[dependencies.littlebotanica]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.littlebotanica]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.littlebotanica]]
    modId="botania"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.littlelogistics]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
