modLoader="javafml"
loaderVersion="[43,)"
license="GNU General Public License v3.0"
licenseURL= "https://github.com/LeoBeliik/LittleBotanics/blob/aac83dd1277d890842db790f183f385297757d7f/LICENSE.md"
issueTrackerURL="https://github.com/LeoBeliik/LittleBotanics/issues"
[[mods]]
modId="littlebotanics"
version="1.${file.jarVersion}"
displayName="Little Botanics"
displayURL="https://www.curseforge.com/minecraft/mc-mods/little-botanics"
authors="LeoBeliik"
logoFile= "littlebotanics_logo.png"
description='''
Addon mod for Little Logistics and Botania that adds a car mana pool and barge mana pool
'''
[[dependencies.littlebotanics]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.littlebotanics]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.littlebotanics]]
    modId="botania"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.littlelogistics]]
    modId="littlelogistics"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
